name: Bug report
description: Report a bug
title: "[bug] <title>"
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
      placeholder: e.g., 500 error calling /predict
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: 1) run backend ... 2) call POST /predict ...
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
